Proyecto/Models/Unidad.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Proyecto.Models
{
    public class Unidad
    {
        [Key]
        [Required]
        public int UnidadMedidaId { get; set; }
        [Required]
        [StringLength(50)]
        public string Codigo { get; set; }
        [Required]
        [StringLength(50)]
        public string Descripcion { get; set; }
        [Required]
        public bool Estado { get; set; }
    }
}

Proyecto/Controllers/UnidadController.cs
using Proyecto.Database;
using Proyecto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto.Controllers
{
    public class UnidadController : Controller
    {
        private TiendaContext context;
        public UnidadController()
        {
            context = new TiendaContext();
        }
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            context.Dispose();
        }
        public ActionResult Index()
        {
            // mostrar todos los registros de las clasificaciones
            var producto = context.unidads.ToList();
            return View(producto);
        }
        public ActionResult Nuevo()
        {
            var unidades = new Unidad();
            return View("UnidadForm", unidades);
        }
        public ActionResult Editar(int id)
        {
            var clasificacionesInDb = context.unidads.SingleOrDefault(c => c.UnidadMedidaId == id);
            if (clasificacionesInDb == null)
                return HttpNotFound();

            return View("UnidadForm", clasificacionesInDb);
        }
        public ActionResult Eliminar(int id)
        {
            var clasificacionesInDb = context.unidads.SingleOrDefault(c => c.UnidadMedidaId == id);
            if (clasificacionesInDb == null)
                return HttpNotFound();

            return View(clasificacionesInDb);
        }

        [HttpPost, ActionName("Eliminar")]
        public ActionResult ConfirmarEliminar(int id)
        {
            var clasificacionesInDb = context.unidads.SingleOrDefault(c => c.UnidadMedidaId == id);
            if (clasificacionesInDb == null)
                return HttpNotFound();

            context.unidads.Remove(clasificacionesInDb);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Guardar(Unidad unidades)
        {
            if (!ModelState.IsValid)
                return View("UnidadForm", unidades);

            if (unidades.UnidadMedidaId == 0)
            {
                context.unidads.Add(unidades);
            }
            else
            {
                var clasificacionesInDb = context.unidads.SingleOrDefault(c => c.UnidadMedidaId == unidades.UnidadMedidaId);
                clasificacionesInDb.Descripcion = unidades.Descripcion;
                clasificacionesInDb.Codigo = unidades.Codigo;
                clasificacionesInDb.Estado = unidades.Estado;
            }
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Detalles(int id)
        {
            var clasificacionesInDb = context.unidads.SingleOrDefault(c => c.UnidadMedidaId == id);
            if (clasificacionesInDb == null)
                return HttpNotFound();

            return View(clasificacionesInDb);
        }

    }
}

Proyecto/Views/Unidad/Detalles.cshtml
@model Proyecto.Models.Unidad

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    <h4>Unidad</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.UnidadMedidaId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Proyecto/Views/Unidad/Eliminar.cshtml
@model Proyecto.Models.Unidad
@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h2> ¿ Esta seguro que desea eliminar el registro ?</h2>
<div>
    <h4>clasficacion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.UnidadMedidaId)</dt>
        <dd>@Html.DisplayFor(model => model.UnidadMedidaId)</dd>

        <dt>@Html.DisplayNameFor(model => model.Descripcion)</dt>
        <dd>@Html.DisplayFor(model => model.Descripcion)</dd>

        <dt>@Html.DisplayNameFor(model => model.Codigo)</dt>
        <dd>@Html.DisplayFor(model => model.Codigo)</dd>

        <dt>@Html.DisplayNameFor(model => model.Estado)</dt>
        <dd>@Html.DisplayFor(model => model.Estado)</dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Proyecto/Views/Unidad/Index.cshtml
@model IEnumerable<Proyecto.Models.Unidad>

@{
    ViewBag.Title = "Index";
}



<h2>Mantenimiento de Unidad</h2>
<p>
    @Html.ActionLink("Nuevo", "Nuevo", null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>Id</th>
        <th>Descripcion</th>
        <th>Codigo</th>
        <th>Estado</th>

    </tr>
    @foreach (var model in Model)
    {
        <tr>
            <td>@Html.DisplayFor(m => model.UnidadMedidaId)</td>
            <td>@Html.DisplayFor(m => model.Descripcion)</td>
            <td>@Html.DisplayFor(m => model.Codigo)</td>
            <td>@Html.DisplayFor(m => model.Estado)</td>

            <td>
                @Html.ActionLink("Editar", "Editar", new { id = model.UnidadMedidaId }, new { @class = "btn btn-info" }) |
                @Html.ActionLink("Detalles", "Detalles", new { id = model.UnidadMedidaId }, new { @class = "btn btn-warning" }) |
                @Html.ActionLink("Eliminar", "Eliminar", new { id = model.UnidadMedidaId }, new { @class = "btn btn-danger" })

            </td>
        </tr>
    }
</table>

Proyecto/Views/Unidad/UnidadForm.cshtml
@model Proyecto.Models.Unidad
@{
    ViewBag.Title = "UnidadForm";
}



<h2>Mantenimiento Unidad</h2>
@using (Html.BeginForm("Guardar", "Unidad"))
{
    @Html.AntiForgeryToken();
    <div class="form-horizontal">
        <h4>Adicion / Edicion </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>

            </div>
        </div>
        <div class="form-group">
            @Html.HiddenFor(model => model.UnidadMedidaId)
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-secondary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}